SYSTEM_PROMPT = "You are a very annoying assistant."
PROMPTS = [
    "What is the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What is the largest planet in our solar system?",
    "Who painted the Mona Lisa?",
    "What is the chemical symbol for gold?",
    "What year did World War II end?",
    "Who invented the telephone?",
    "What is the capital of Japan?",
    "What is the main ingredient in guacamole?",
    "Who wrote the novel '1984'?",
    "What is the boiling point of water in Celsius?",
    "Who was the first person to walk on the moon?",
    "What is the largest ocean on Earth?",
    "Who composed the 'Moonlight Sonata'?",
    "What is the capital of Australia?",
    "Who discovered penicillin?",
    "What is the smallest prime number?",
    "Who painted 'Starry Night'?",
    "What is the longest river in the world?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What is the speed of light in vacuum?",
    "Who is known as the father of modern physics?",
    "What is the largest desert in the world?",
    "Who invented the light bulb?",
    "What is the capital of Brazil?",
    "Who wrote 'Pride and Prejudice'?",
    "What is the chemical formula for water?",
    "Who discovered gravity?",
    "What is the tallest mountain in the world?",
    "Who painted the Sistine Chapel ceiling?",
    "What is the largest mammal on Earth?",
    "Who invented the World Wide Web?",
    "What is the capital of Egypt?",
    "Who wrote 'The Great Gatsby'?",
    "What is the freezing point of water in Fahrenheit?",
    "Who discovered America?",
    "What is the smallest country in the world?",
    "Who composed the 'Fifth Symphony'?",
    "What is the capital of Russia?",
    "Who invented the theory of evolution?",
    "What is the hardest natural substance on Earth?",
    "Who wrote 'Hamlet'?",
    "What is the largest continent?",
    "Who painted 'The Last Supper'?",
    "What is the capital of Canada?",
    "Who invented the periodic table?",
    "What is the deepest point in the ocean?",
    "Who wrote 'War and Peace'?",
    "What is the most abundant gas in Earth's atmosphere?",
    "Who is considered the father of modern computer science?"
]
